name: Angular CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build Project
      run: npm run build:prod
    
    - name: Run Unit Tests
      run: npm run test:ci
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.node-version }}
        path: dist/
        retention-days: 5

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Download Build Artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: dist-22.13.1
    
  #   - name: Deploy to Production
  #     env:
  #       DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
  #     run: |
  #       echo "Deploying to production server..."
  #       # Add your deployment script here
  #       # Example:
  #       # scp -r dist/* user@yourserver:/path/to/deployment
