name: Node.js CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
    
    # - name: Lint Code
    #   run: npm run lint
    
    - name: Run Unit Tests
      run: npm run test:ci
    
    - name: Build Project
      run: npm run build
    
    # - name: Run E2E Tests
    #   run: npm run e2e
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.node-version }}
        path: dist/
        retention-days: 5

  # Optional deployment job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy from main branch
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-22.13.1  # Use the latest Node.js version build
    
    - name: Deploy to Production
      env:
        DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "Deploying to production server..."
        # Add your deployment script here
        # Example:
        # scp -r dist/* user@yourserver:/path/to/deployment
